apiVersion: v1
kind: Pod 
metadata:
  name: traffic-gen
  labels:
    app: traffic-gen 
spec:
  containers:
    - name: traffic-gen 
      image: mtsfy/traffic-gen:1.0.0
      args:
        - "color-api-svc.dev.svc.cluster.local/api?format=json"
        - ".5"