apiVersion: v1
kind: Pod
metadata:
  name: color-backend
  labels:
    app: color-api
    environment: local
    tier: backend
spec:
  containers:
    - name: color-api-backend
      image: mtsfy/color-api:1.1.0
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: color-frontend
  labels:
    app: color-api
    environment: local
    tier: frontend
spec:
  containers:
    - name: nginx-frontend
      image: nginx:1.27.0
      ports:
        - containerPort: 80