apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  containers:
  - name: traffic-generator
    image: mtsfy/traffic-gen:1.0.0
    args:
      - "color-api-clusterip/api?format=json"
      - ".5"
