apiVersion: v1
kind: Service
metadata:
  name: color-api-clusterip
  labels:
    app: color-api-clusterip
spec:
  type: ClusterIP
  selector:
    app: color-api
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: color-api-nodeport
  labels:
    app: color-api-nodeport
spec:
  type: NodePort
  selector:
    app: color-api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007